---
version: "3"

services:
  db:
    image: postgres:15.0
    container_name: pg-database
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${PG_ADMIN_USER}
      - POSTGRES_PASSWORD=${PG_ADMIN_PWD}
      - POSTGRES_DB=bess
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_ADMIN_USER} -d ${PG_ADMIN_PWD}"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - bess

volumes:
  pg-data:
  data:

networks:
  bess:
    external: true
